const ADD_TODO = "add todo"
const TOGGLE_TODO = "TOGGLE_TODO"
const DELETE_TODO = "DELETE_TODO"
const GET_ALL_TODO_LIST_FROM_URL = "GET_ALL_TODO_LIST_FROM_URL"

export {
    ADD_TODO,
    TOGGLE_TODO,
    DELETE_TODO,
    GET_ALL_TODO_LIST_FROM_URL
}